import math
import functools


#1 If we list all the natural numbers below 10 that are multiples of 3 or 5, we 3,5,6,9 get  and . The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.
# list=list()
# count=0
#
# for i in range(1000):
#     if i % 3==0 or i % 5==0:
#         count+=i
#
# print(f"Ilk 1000 sayinin bolenleri toplami  {count}")



#2 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms will be: 10

                    #1 2 3 5 8 13 21 34 55 89

     #By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#
# fibonacci_list=list()
# fibonacci_list.append(1)
# fibonacci_list.append(2)
# counter=0
# index=2
#
# while index < 4000000:
#     if fibonacci_list[index-1]+fibonacci_list[index-2] < 4000000:
#         fibonacci_list.append(fibonacci_list[index-1]+fibonacci_list[index-2])
#         index+=1
#     else:
#         break
#
# for i in fibonacci_list :
#     if i % 2 ==0:
#         counter+=i
#
# print(counter)

#3   13195 prime factor are 5 7 13 29
    # find 600851475143


# def is_prime(n):
#     isprime = True
#     for i in range(2, int(math.sqrt(n)+1)):
#         if n % i == 0:
#             isprime = False
#             continue
#     return isprime
#
# num=600851475143
# biggest_prime=1
#
# for i in range(2,int(math.sqrt(num))+1):
#     if num % i == 0 and is_prime(i):
#         biggest_prime=i
#
# print(biggest_prime)

# def is_palindrome(n):
#     strNum = str(n)
#     reversedStrNum = strNum[::-1]
#     if strNum == reversedStrNum:
#         return True
#     else:
#         return False
#
#4
# biggest_palindrome = 0
#
# for i in range(100,1000):
#     for j in range(100,1000):
#         if is_palindrome(i*j) and biggest_palindrome < i*j:
#             biggest_palindrome = i*j
#
# print(biggest_palindrome)

# 5
# def gcd(x,y):
#     return math.gcd(x,y)
#
# def lcm(x,y):
#     return x*y//gcd(x,y)
#
#
# list=range(1,21)
#
# result=functools.reduce(lcm,list)
# print(result)

#6
# def square_root(n):
#     sum=0
#     for i in range(1,n+1,1):
#         sum+= i**2
#     return sum
#
# def square_root_total(n):
#     sum=0
#     for i in range(1,n):
#         sum= (((n)*(n+1))//2) **2
#     return sum
#
# def range_squares(n):
#     result=square_root_total(n)-square_root(n)
#     print(result)
#     return result
# range_squares(100)


        #7
#
# def is_prime(n):
#     prime = True
#     if n == 2:
#      return True
#     else:
#         for i in range(2, int(n**0.5)+1):
#             if n % i == 0:
#                 prime = False
#                 break
#         return prime
#
#
# i=2
# count = 0
# while True:
#      if is_prime(i):
#             count += 1
#      if count == 10001:
#             print(i)
#             break
#      i+=1

    #8
#
# num="""73167176531330624919225119674426574742355349194934
# 96983520312774506326239578318016984801869478851843
# 85861560789112949495459501737958331952853208805511
# 12540698747158523863050715693290963295227443043557
# 66896648950445244523161731856403098711121722383113
# 62229893423380308135336276614282806444486645238749
# 30358907296290491560440772390713810515859307960866
# 70172427121883998797908792274921901699720888093776
# 65727333001053367881220235421809751254540594752243
# 52584907711670556013604839586446706324415722155397
# 53697817977846174064955149290862569321978468622482
# 83972241375657056057490261407972968652414535100474
# 82166370484403199890008895243450658541227588666881
# 16427171479924442928230863465674813919123162824586
# 17866458359124566529476545682848912883142607690042
# 24219022671055626321111109370544217506941658960408
# 07198403850962455444362981230987879927244284909188
# 84580156166097919133875499200524063689912560717606
# 05886116467109405077541002256983155200055935729725
# 71636269561882670428252483600823257530420752963450"""
#
# list=num.split("\n")
# number=""
#
# for i in list:
#     number=number+i
# product = 1
#
# for i in range(1,len(number)-12):
#     aux=1
#     for j in number[i:i+13]:
#         aux*=int(j)
#     if aux>product:
#         product=aux
#
# print(product)


#
# for i in range(1,1000):
#         for j in range(1,1000-i):
#             k = 1000-i-j
#             if k*k == i*i + j*j:
#                 print(i*j*k)
#                 break




# def is_prime(n):
#     prime=True
#     if n < 2:
#         prime=False
#         return  prime
#     if n == 2:
#         prime=True
#         return prime
#     else:
#         for i in range(2, int(math.sqrt(n)+1)):
#             if n % i == 0:
#                 prime=False
#                 break
#         return prime
#
# sum=0
# number=2
# while True:
#     if is_prime(number):
#         sum+=number
#     if number==2000000:
#         break
#     number+=1
#
# print(sum)

            #11
# numbers="""8 2 22 97 38 15 0 40 0 75 4 5 7 78 52 12 50 77 91 8
# 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 4 56 62 0
# 81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 3 49 13 36 65
# 52 70 95 23 4 60 11 42 69 24 68 56 1 32 56 71 37 2 36 91
# 22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
# 24 47 32 60 99 03 45 2 44 75 33 53 78 36 84 20 35 17 12 50
# 32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
# 67 26 20 68 2 62 12 20 95 63 94 39 63 8 40 91 66 49 94 21
# 24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
# 21 36 23 9 75 0 76 44 20 45 35 14 0 61 33 97 34 31 33 95
# 78 17 53 28 22 75 31 67 15 94 3 80 4 62 16 14 9 53 56 92
# 16 39 5 42 96 35 31 47 55 58 88 24 0 17 54 24 36 29 85 57
# 86 56 0 48 35 71 89 7 5 44 44 37 44 60 21 58 51 54 17 58
# 19 80 81 68 5 94 47 69 28 73 92 13 86 52 17 77 4 89 55 40
# 4 52 8 83 97 35 99 16 7 97 57 32 16 26 26 79 33 27 98 66
# 88 36 68 87 57 62 20 72 3 46 33 67 46 55 12 32 63 93 53 69
# 4 42 16 73 38 25 39 11 24 94 72 18 8 46 29 32 40 62 76 36
# 20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 4 36 16
# 20 73 35 29 78 31 90 1 74 31 49 71 48 86 81 16 23 57 5 54
# 1 70 54 71 83 51 54 69 16 92 33 48 61 43 52 1 89 19 67 48"""

# rows=numbers.split("\n")
#
# list=list()
# for i in range(0,20):
#     elements=rows[i].split(" ")
#     list.append(elements)
#
# def left_right():
#     largest_product=0
#     for i in range(0,20):
#         for j in range(0,17):
#             product=1
#             for k in range(0,4):
#                 product*= int(list[i][j+k])
#                 if product > largest_product:
#                     largest_product=product
#     return largest_product
#
# def up_down():
#     largest_product = 0
#     for i in range(0, 17):
#         for j in range(0, 20):
#             product = 1
#             for k in range(0, 4):
#                 product *= int(list[i+k][j])
#                 if product > largest_product:
#                     largest_product = product
#     return largest_product
#
# def diagonal_first():
#     largest_product = 0
#     for i in range(0, 17):
#         for j in range(0, 17):
#             product = 1
#             for k in range(0, 4):
#                 product *= int(list[i+k][j + k])
#                 if product > largest_product:
#                     largest_product = product
#     return largest_product
#
# def diagonal_second():
#     largest_product = 0
#     for i in range(0, 17):
#         for j in range(0, 17):
#             product = 1
#             for k in range(0, 4):
#                 product *= int(list[i+k][19-j-k])
#                 if product > largest_product:
#                     largest_product = product
#     return largest_product
#
#
#
#
# results=[]
# results.append(left_right())
# results.append(up_down())
# results.append(diagonal_first())
# results.append(diagonal_second())
# print(max(results))



        #12
#
# def bolen_sayisi(x):
#     bolen=1
#     for i in range(2,int(math.sqrt(x))+1):
#         if x % i == 0:
#             bolen += 1
#
#     return bolen*2
#
#
#
# n=1
# while True:
#     number=(n*(n+1))/2
#     if bolen_sayisi(number) > 500:
#         print(int(number))
#         break
#     n=n+1

